### ISSUE TITLE
Notes section not keeping newline characters

### ISSUE THREAD

**Issue by hanakims** [cse110-sp21-group12/cse110-sp21-group12#118]
## Expected Behavior
When a user enters a note with new lines and leaves the page and comes back to it, the page should display the original note with the new line characters as the user typed in

## Actual Behavior
When the user leaves the page and returns, the notes are not displaying the newline characters and all the text is in one large block

## Specifications

  - Version: deployed website from the testing branch
  - Platform: chrome

**Comment by DustinLin** [comment]
Closed with #125
