### ISSUE TITLE
Fixing monthly icons on yearly overview on resize

### ISSUE THREAD

**Issue by hanakims** [cse110-sp21-group12/cse110-sp21-group12#119]
## Expected Behavior
When resizing the yearly overview page, the monthly buttons should still look proportional and the image in each one should fit. 

## Actual Behavior
When the screen is resized, the month icon images overflow because the button sizes do not resize correctly with the images.

## Specifications

  - Version: deployed website from the testing branch
  - Platform: chrome

**Comment by DustinLin** [comment]
closed with #121
